# Generated by Django 3.1.3 on 2020-11-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeblog', '0016_auto_20201126_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
