# Generated by Django 3.1.3 on 2020-12-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeblog', '0018_post_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
